# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False, verbose_name='Jsem tady')),
                ('photo', models.ImageField(upload_to='nudni/artist/', verbose_name='Profilovka')),
                ('intro', models.TextField(verbose_name='Text\xedk pod profilovku')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Um\u011blec',
                'verbose_name_plural': 'Um\u011blci',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nadpis')),
                ('description', models.CharField(max_length=400, verbose_name='popis')),
                ('photo', models.ImageField(upload_to='nudni/work/', verbose_name='Fotka')),
            ],
            options={
                'verbose_name': 'Pr\xe1ce',
                'verbose_name_plural': 'Pr\xe1ce',
            },
        ),
    ]
